name: cna2gex
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - r
dependencies:
  - black=19.10b0
  - gdown=4.5.3
  - ipython=8.3.0
  - ipykernel=6.17.1
  - matplotlib=3.6.2
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=22.3.1
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - rpy2=3.5.1
  - scikit-learn=1.0.2
  - scipy=1.9.3
  - selenium=3.141.0
  - setuptools=59.5.0
  - tensorboard=2.8.0
  - tqdm=4.64.0
  - webdriver-manager=3.8.4
